package com.example.myapp;

//import com.codename1.admob.AdMobManager;
import com.codename1.system.Lifecycle;
import com.codename1.ui.Display;
import com.codename1.ui.Toolbar;
import com.example.util.Constants;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
//./run.sh
public class MyApp extends Lifecycle {
    //public static AdMobManager admob;
    public static int DEVICE_HEIGHT;
    public static int DEVICE_WIDTH;
    public static float WIDTH_SCALE;
    public static float HEIGHT_SCALE;

    @Override //entry point 
    public void runApp() {
    }

    @Override
    public void init(Object context) {
        //force orientation landscape, then we grab the proper device width and height and scales so that the app is optimized
        if (Display.getInstance().isPortrait() && Display.getInstance().getPlatformName().equals("and")) {
            Display.getInstance().lockOrientation(false);
            DEVICE_HEIGHT =  Display.getInstance().getDisplayWidth() - (int) (Display.getInstance().getDisplayWidth() * .07);
            DEVICE_WIDTH = Display.getInstance().getDisplayHeight() + (int) (Display.getInstance().getDisplayHeight() * .03);
            WIDTH_SCALE = (float) DEVICE_WIDTH / (float) Constants.GAME_WIDTH;
            HEIGHT_SCALE = (float) DEVICE_HEIGHT / (float) Constants.GAME_HEIGHT;
        } else {
            Display.getInstance().lockOrientation(false);
            DEVICE_HEIGHT =  Display.getInstance().getDisplayHeight();
            DEVICE_WIDTH = Display.getInstance().getDisplayWidth();
            WIDTH_SCALE = (float) DEVICE_WIDTH / (float) Constants.GAME_WIDTH;
            HEIGHT_SCALE = (float) DEVICE_HEIGHT / (float) Constants.GAME_HEIGHT;
        }

        //set up admobid to correspond with apple/android 
        String admobId = "ca-app-pub-9749305699775932~6495740792";
        if(Display.getInstance().getPlatformName().equals("ios")){
            admobId = "ca-app-pub-9749305699775932~9916111055";
        }
        //admob = new AdMobManager(admobId);
        Toolbar.setGlobalToolbar(false);
        Game.game = Game.getGame();
        Game.game.startGameThread();
    }
}
